import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/store/provider'
import { AuthProvider } from "@/utils/authContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SPK with SAW method',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <AuthProvider>
          <body className={inter.className}>{children}</body>
        </AuthProvider>
      </Providers>
    </html>
  )
}
